version: '3.8'

services:
  db:
    image: postgres:13
    container_name: radiolatino_container
    restart: always
    environment:
      POSTGRES_USER: radiolatino_user
      POSTGRES_PASSWORD: CQnQZbKc0UPNfVZZYRzOfuRCmKdWZceX
      POSTGRES_DB: emisoradb2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radiolatino_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
